<a href="https://colab.research.google.com/github/victoriaazabel/SEdigitalorganizations/blob/main/VictoriaZabel_homework_3_student.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
#hide
! [ -e /content ] && pip install -Uqq fastbook
import fastbook
from fastai.vision.all import *
from fastbook import *
fastbook.setup_book()

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 719.8/719.8 kB 34.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.0/7.0 MB 93.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 71.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 468.7/468.7 kB 42.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 212.2/212.2 kB 21.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 110.5/110.5 kB 15.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 132.9/132.9 kB 17.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 57.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 200.1/200.1 kB 25.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 91.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.2/114.2 kB 13.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 264.6/264.6 kB 25.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

# Introduction to Artificial Neural Networks

Please read the introdcution of neuronal networks of the book *Hands-On Machine Learning with Scikit-Learn, Keras & TensorFlow*, p. 299-316.

1. Why have neural networks, even though they were invented early on, only now caught on?

2. What is a percepton and a threshold logic unit (TLU)? Try to define a linear function and a step function of your choice, use some values of your choice and explain what might be the result of the percepton. (maybe using max. two TLU's)

3. What is a fully connected layer and an output layer? Why can we easily combine the equations of multiple instances into a fully connected layer?

4. What problem did Marvin Minsky and Seymour Paper highlight that perceptrons could not solve? What is a possible solution?

5. What is a deep neuronal network? What are hidden layers? What means feedforward neural network (FNN).

6. Try to explain how backpropagation works! (In Addition, you can have a look to the following example, which tries manually to compute the backprogation of a simple linear network. https://mattmazur.com/2015/03/17/a-step-by-step-backpropagation-example/ OR you can also read through the Google Colab [04_mnist_basics.ipynb](https://colab.research.google.com/github/fastai/fastbook/blob/master/04_mnist_basics.ipynb#scrollTo=t1DK6o-gckCy))

6. Why do we need activation functions, wouldn't it be easier just using linear functions?


## Answers

1. Neural networks, although invented in 1943, have only recently caught on. This is because many other architectures and training techniques were created that were more powerful and offered better results. This caused the progress of neural networks to slow down. Nowadays, there is more data as well as increased computing power, meaning that neural networks are more successful in working on large and complex machine learning projects. Among others, the improvement in training algorithms has had a positive impact on neural networks of today.

2. Percepton and Threshold Logic Units (TLU's) are simple artificial neural networks, with perceptons being based on TLU's. In their cases the inputs are numeric values rather than binary ones. Perceptons commonly use the Heaviside Step Function, whereas TLU's can be used for simple linear binary classification. A linear function could be z = w⊺ x + b. The result of which will be applied to the step function, in our example the Heavyside Step Function, using input weights (w) and the bias (b) as parameters (= step(z)). Example inputs would be 1, 2, and 3 weighted at 2, 4, 8 respectively. After applying the weights to the inputs, the step function and the bias are applied to the outcome which will have the values of 0 or 1, 0 if z < 0 and 1 if z > 0.

3. A fully connected, or dense, layer is a perceptron composed of one or more TLU's compromised into one layer. In this case, every TLU is connected to every input (input layer). An output layer on the other hand, is the final output produced by the layer of TLU's. Combining equations of multiple instances into a fully connected layer can be done because of linear algebra, specifically matrices. One example of this is done by “broadcasting” in which the process of adding a vector to a matrix allows you to add it to every row within the matrix.

4. According to Marvin Minsky and Seymour Paper, perceptrons cannot solve the problem of solving trivial problems, such as exclusive OR (XOR) problems. Although this is also the case for other linear classification models, perceptrons were held to a higher regard leading to a greater disapointment. However, a possible solution of this would be using Multilayer Perceptrons (MLP's) that stack multiple perceptrons and are able to solve XOR problems.

5. A deep neuronal network is a type of artificial neural network that contains multiple, or a "deep stack", of hidden layers. While it used to mean a network with two or more hidden layers, nowadays the definition and boundaries of hidden layers in neural networks is unclear. As such, hidden layers are the TLU layers between the input and the final TLU layer (output layer) and are categorized into lower layers if closer to the input and upper layers if closer to the output. Feedforward Neural Network (FNN) are architectures in which the signal flows from the inputs to the outputs, namely in in one direction. 

6. Backpropagation is an algorithm used when training feedforward neural networks. Here, the derivative of layers in neural networks is calculated. It is a combination of reverse-mode autodiff and gradient descent to improve weights connection and using error gradients in order to train neural networks.

7. Activation functions, such as the sigmoid function, are needed because they are able to solve complex problems and develop complex representations.
Using linear functions would not be easier because the chaining of multiple linear functions will only result in more linear functions, meaning that you would not be able to solve complex problems. Thus, with the absence of activation functions, neural networks would work with their inputs as a linear regression model would. The main difference here is that you are able to differentiate a function, which makes less sense in a linear function as this would result in a constant.

## Ideas for the learning portfolio:

1) For example, you could train a single TLU to classify iris flowers based on petal length and width in the !!!pyTorch!! environment.

2) You could add to our king county housepricing ML project a neuronal network and compare it to the other models.

In [6]:
from sklearn import datasets
iris = datasets.load_iris()

# A traditional approach: training a digit classifier and learning pyTorch tensors.

For this assignment, I ask you to read the Google Colab [04_mnist_basics.ipynb](https://colab.research.google.com/github/fastai/fastbook/blob/master/04_mnist_basics.ipynb#scrollTo=t1DK6o-gckCy) to the beginning of the chapter *Stochastic Gradient Descent (SGD)*. 

First, try to summarize what we know about pyTorch tensors by trying to predict whether we have a 1 or a 7 in the MNIST dataset using a traditional rule-based programming approach. Therefore use pyTorch tensors for the entire tasks and fulfill the following steps:

1) Randomly split the MNIST dataset (1 and 7) into a training dataset and a test dataset in a ratio of 80:20.

2) Instead of using an optimal 1 or 7 with the mean over the training dataset, try to calculate the sum of the distances to all instances in the training set for each instance in the test dataset. You can use the L2 norm. 

3) For each instance in the test set, decide if it is a 1 or 7 and calculate the precision.

Do we get a similar good result?


In [41]:
# From 04 MNIST: experimenting with the dataset before answering the questions

#path = untar_data(URLs.MNIST_SAMPLE) # only contains 3 and 7 cuz of sample so...
path = untar_data(URLs.MNIST)

#hide
Path.BASE_PATH = path

path.ls()



(#2) [Path('training'),Path('testing')]

In [18]:
#[Path('cleaned.csv'),Path('item_list.txt'),Path('trained_model.pkl'),Path('models'),Path('valid'),Path('labels.csv'),Path('export.pkl'),Path('history.csv'),Path('train')]

(path/'training').ls()

[Path('training/7'),Path('training/1')]

one = (path/'training'/'1').ls().sorted()
seven = (path/'training'/'7').ls().sorted()
one


(#6742) [Path('training/1/10006.png'),Path('training/1/10007.png'),Path('training/1/1002.png'),Path('training/1/10020.png'),Path('training/1/10027.png'),Path('training/1/1003.png'),Path('training/1/10040.png'),Path('training/1/10048.png'),Path('training/1/10058.png'),Path('training/1/10067.png')...]

In [23]:
#im1_path = one[1]
#im1 = Image.open(im1_path)
#im1

im7_path = seven[1]
im7 = Image.open(im7_path)
im7

#array(im7)[4:10,4:10]

tensor(im7)[4:10,4:10]

im7_t = tensor(im7)
df = pd.DataFrame(im7_t[4:15,4:22])
df.style.set_properties(**{'font-size':'6pt'}).background_gradient('Greens')

In [25]:
#1. 

import torch
from torchvision.datasets import MNIST

training_set7, validation_set7 = torch.utils.data.random_split(seven, [0.8, 0.2])

training_set1, validation_set1 = torch.utils.data.random_split(one, [0.8, 0.2])

In [34]:
#2.

tensors7 = [tensor(Image.open(o)) for o in training_set7]
tensors1 = [tensor(Image.open(o)) for o in training_set1]
len(tensors1),len(tensors7)

stacked7 = torch.stack(tensors7).float()/255
stacked1 = torch.stack(tensors1).float()/255
stacked1.shape

mean7 = stacked7.mean(0)
#show_image(mean7);

mean1 = stacked1.mean(0)
#show_image(mean1);

a7 = stacked7[1]
#show_image(a7);

a1 = stacked7[1]

l2n7 = ((a7 - mean7)**2).mean().sqrt()
l2n7

l2n1 = ((a1 - mean1)**2).mean().sqrt()
l2n1

print(l2n7, l2n1)

tensor(0.1833) tensor(0.3062)


In [56]:
#3. 

def mnist_distance(a,b): return (a-b).abs().mean((-1,-2))
mnist_distance(a1, mean1)
mnist_distance(a7, mean7)

test1_tens = torch.stack([tensor(Image.open(o)) 
                            for o in validation_set1])
test1_tens = test1_tens.float()/255
test7_tens = torch.stack([tensor(Image.open(o)) 
                            for o in validation_set7])
test7_tens = test7_tens.float()/255
test1_tens.shape,test7_tens.shape

def is_1(x): return mnist_distance(x, mean1) < mnist_distance(x, mean7)

def is_7(x): return mnist_distance(x, mean7) < mnist_distance(x, mean1)

distance_test1 = mnist_distance(test1_tens, mean1)
distance_test1, distance_test1.shape

is_1(a1), is_1(a1).float() # for a singlet hing this is false
is_7(a7), is_7(a7).float() # "" true

is_7(test7_tens)
is_1(test1_tens)

accuracy_1 = is_1(test1_tens).float() .mean()
accuracy_7 = is_7(test7_tens).float().mean()

accuracy_1, accuracy_7, (accuracy_1+accuracy_7) / 2

(tensor(0.9985), tensor(0.8148), tensor(0.9067))

# Stochastic Gradient Descent (SGD)

For this exercise I ask you to read the chapter Stochastic Gradient Descent (SGD) from the Google Colab 04_mnist_basics.ipynb in paralell. The chapter starts with a single TLU, compare p. 304 in "Hands on Machine Learning". Go through all 7 steps which are an easy example of how Stochastic Gradient Descent works.

Our goal is to train a single TLU, which can decide if one number is larger then the other one. Therefore we create 100 random pairs with pyTorch and create a target vector which is eather 1 or 0.


1. Initialize the weights.

2. For each image, use these weights to predict whether it appears to be a 3 or a 7.

3. Based on these predictions, calculate how good the model is (its loss).

4. Calculate the gradient, which measures for each weight, how changing that 
weight would change the loss

5. Step (that is, change) all the weights based on that calculation.

6. Go back to the step 2, and repeat the process.

7. Iterate until you decide to stop the training process (for instance, because the model is good enough or you don't want to wait any longer).

In [57]:
x = torch.randn((100, 2))
y = torch.where(x[:,0] > x[:,1], 1.0, 0.0)
print(x)
print(y)

tensor([[-0.0661, -0.2025],
        [-0.6795,  0.0580],
        [-0.4715,  1.3066],
        [-0.5035, -0.9364],
        [ 0.8816,  1.2512],
        [-0.0529, -1.5510],
        [ 1.1730, -1.0408],
        [ 0.8998,  0.7058],
        [ 0.6230, -0.7351],
        [-1.5187, -0.9034],
        [-0.4708,  0.7341],
        [-0.6009,  0.5453],
        [-2.0567, -0.7157],
        [ 0.8060,  0.6183],
        [ 1.7232,  1.0612],
        [-0.5030,  0.2772],
        [-0.3278,  1.1425],
        [ 1.3275,  1.5741],
        [-1.0005, -0.4779],
        [ 0.7259, -1.2694],
        [-1.1191, -1.6090],
        [ 0.9179,  0.6802],
        [ 0.8910, -0.5190],
        [-1.5117,  1.6752],
        [-0.7739,  0.7662],
        [-1.0434,  0.9744],
        [-0.2142, -0.5244],
        [-1.4998, -0.9746],
        [-0.2332, -1.6942],
        [-0.4870,  0.7598],
        [ 0.0228,  0.9663],
        [ 0.6817,  2.6798],
        [ 1.8297, -0.3295],
        [-0.5554, -0.0344],
        [-2.1779,  0.9070],
        [ 1.3068, -1

Your task is to create a function f that is a single TLU, meaning that it summarizes x with weights a, b, c:

$ax_0+bx_1+c$

In Addition we are using a *sigmoid()* function as step function.

$f = \text{sigmoid}(ax_0+bx_1+c)$

In [59]:
def f(x, params):
    a,b,c = params
    d = a * x [:,0] + b * x [:,1] + c

    return sigmoid(d)

print(f(x, [3,-2,1]))

tensor([7.6971e-01, 2.3968e-01, 4.6192e-02, 7.9616e-01, 7.5812e-01, 9.8098e-01, 9.9864e-01, 9.0787e-01, 9.8712e-01, 1.4812e-01, 1.3230e-01, 1.3087e-01, 2.3231e-02, 8.9857e-01, 9.8283e-01, 2.5664e-01,
        9.3780e-02, 8.6228e-01, 2.6002e-01, 9.9672e-01, 7.0278e-01, 9.1631e-01, 9.9109e-01, 1.0216e-03, 5.4472e-02, 1.6641e-02, 8.0314e-01, 1.7507e-01, 9.7561e-01, 1.2125e-01, 2.9646e-01, 8.9937e-02,
        9.9921e-01, 3.5494e-01, 6.4367e-04, 9.9917e-01, 9.5396e-02, 1.2501e-01, 8.4759e-01, 9.9765e-01, 9.6319e-01, 1.4710e-03, 9.2763e-02, 9.8557e-01, 9.8938e-01, 7.3512e-02, 9.8145e-01, 9.0163e-01,
        8.9450e-01, 9.9771e-01, 9.6892e-01, 3.7075e-01, 4.9179e-01, 9.9765e-01, 1.8825e-01, 1.7971e-01, 8.2720e-01, 9.8746e-01, 1.8810e-03, 1.5034e-01, 9.9893e-01, 9.9865e-01, 3.1266e-04, 1.5699e-01,
        9.3052e-01, 3.7132e-01, 7.7620e-01, 4.6216e-01, 6.3180e-03, 2.3113e-04, 9.8936e-01, 9.5790e-01, 9.9945e-01, 8.8188e-01, 4.7158e-02, 7.2814e-01, 9.7271e-01, 6.5612e-01, 4.4658e-01, 1.3936e-02,


In addition to our TLU function, we need a loss function. Your task is to implement a absolute difference loss function, $∑|x_i-y_i|$, which counts the number of wrong guesses.

In [70]:
def mae(preds, targets): 
  return (preds - targets).abs().mean()

Try to train your single TLU with the absolute difference loss function, use the following code. Choose an appropriate step weight `lr` and try to explain what is happing in each line.

In [90]:
lr = 0.09
params = torch.randn(3).requires_grad_()

def apply_step(params, prn = True):
    preds = f(x, params)
    loss = mae(preds, y)
    loss.backward()
    params.data -= lr * params.grad.data
    params.grad = None
    if prn: print(params);print(loss.item())
    return preds


for i in range(50): apply_step(params)

tensor([-0.6497, -0.1971, -0.4248], requires_grad=True)
0.5683578252792358
tensor([-0.6386, -0.2101, -0.4241], requires_grad=True)
0.5651119351387024
tensor([-0.6273, -0.2231, -0.4235], requires_grad=True)
0.5618411302566528
tensor([-0.6160, -0.2361, -0.4228], requires_grad=True)
0.5585464239120483
tensor([-0.6046, -0.2492, -0.4220], requires_grad=True)
0.5552288889884949
tensor([-0.5931, -0.2622, -0.4212], requires_grad=True)
0.5518896579742432
tensor([-0.5816, -0.2752, -0.4204], requires_grad=True)
0.5485299229621887
tensor([-0.5700, -0.2882, -0.4195], requires_grad=True)
0.5451509356498718
tensor([-0.5583, -0.3013, -0.4186], requires_grad=True)
0.5417540073394775
tensor([-0.5465, -0.3143, -0.4177], requires_grad=True)
0.5383406281471252
tensor([-0.5347, -0.3273, -0.4167], requires_grad=True)
0.5349120497703552
tensor([-0.5229, -0.3403, -0.4156], requires_grad=True)
0.5314698815345764
tensor([-0.5110, -0.3532, -0.4146], requires_grad=True)
0.5280154347419739
tensor([-0.4990, -0.3662,

Write a line of code that counts the number of wrong predictions, rounding your predictions with *round()*.

In [91]:
preds = f(x, params)

roundpreds = preds.round()
print(roundpreds)
print(y)
wr_preds = (y - roundpreds).abs().sum()
print(wr_preds)

tensor([0., 0., 0., 1., 0., 1., 1., 0., 1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 1., 0., 1., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 0., 0.,
        1., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 1., 0., 1., 0., 0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0.,
        0., 1., 1., 0.], grad_fn=<RoundBackward0>)
tensor([1., 0., 0., 1., 0., 1., 1., 1., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0., 1., 1., 1., 0., 0., 1., 1., 0., 1., 1.,
        1., 1., 1., 0., 0., 1., 0., 0., 1., 1., 0., 0., 1., 1., 0., 0., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 1., 1., 0., 0., 1., 0., 1., 1., 1., 1., 0., 1., 1., 0., 0., 1., 1., 0., 0., 1.,
        0., 1., 1., 1.])
tensor(27., grad_fn=<SumBackward0>)
